export const teachingBlocks = [
  {
    id: "TB-CH01-KP001",
    chapterId: "01",
    knowledgeId: "KP-001",
    title: "项目：独特成果与完成状态",
    explanation: "项目是在独特情境中创造价值、并具有完成状态的临时性倡议。判断时先看工作是否产生独特成果，再看是否存在明确的完成与移交；仅仅有期限并不足以说明它是项目。",
    examLogic: "题目常用“只有几周”“每年重复”等表面线索干扰判断。核心仍是独特成果与持续重复业务的区别。",
    decisionRule: "先问：这项工作是否创造一个独特成果并在完成后移交？是，则倾向项目；若只是重复维持既有业务，则倾向运营。",
    commonTrap: "把 temporary 直接等同于 project，或把重复出现直接等同于 operations。",
    example: "企业用六个月设计并部署仓储机器人，验收后交给运营团队维护：设计部署是项目，后续重复维护是运营。",
    source: "03_章节讲义/01_考试地图与项目基础_Foundation.md",
    casePrompt: "公司每年在不同城市举办新品发布会，每场地点、干系人和目标情境不同。单场活动更可能属于什么？",
    caseExpected: ["项目"],
    recallPrompt: "不看讲义，用一句话说明判断“项目”的两个核心线索。",
    recallKeywords: ["独特", "完成"],
    practiceQuestionId: "KP-FOUND-002",
    variationQuestionId: "KP-FOUND-003",
    remediation: "先忽略持续时间，找题目中的“独特成果”和“完成/移交点”。如果工作完成后进入持续重复维护，前半段通常是项目，后半段通常是运营。",
  },
  {
    id: "TB-CH01-KP002",
    chapterId: "01",
    knowledgeId: "KP-002",
    title: "运营：持续重复地维持业务",
    explanation: "运营以持续、重复地维持业务为核心。某项安排即使只持续几周，只要其本质仍是按既有流程重复提供服务，也可能属于运营。",
    examLogic: "考试会用“临时夜班”“旺季专项”等词制造临时性错觉；必须判断工作本质是否仍是重复维持业务。",
    decisionRule: "若活动每天按相同流程反复执行、目标是维持既有服务，且没有独特交付成果，应优先判断为运营。",
    commonTrap: "看到开始和结束日期就直接选择项目。",
    example: "物流中心节庆期间连续三周按相同流程分拣包裹，节后取消夜班：这仍是限时运营安排。",
    source: "03_章节讲义/01_考试地图与项目基础_Foundation.md",
    casePrompt: "客服中心为促销季临时增开两周晚班，仍使用相同脚本处理日常咨询。这更可能属于什么？",
    caseExpected: ["运营"],
    recallPrompt: "为什么“只有三周”不能单独证明一项工作是项目？",
    recallKeywords: ["重复", "维持"],
    practiceQuestionId: "KP-FOUND-001",
    variationQuestionId: "KP-FOUND-003",
    remediation: "把“持续多久”和“工作本质”分开。只要核心是在相同流程中重复维持业务，即使临时加班或限时运行，也仍可能是运营。",
  },
] as const;
